### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by majbc1999** [juresternad/letalski-promet#1]
Na repozitoriju imata nekaj "šare", ki nanj ne sodi: mapa [__pycache__](https://github.com/juresternad/letalski-promet/tree/main/__pycache__) na primer vsebuje nekaj predpomnilniških datotek, ki se avtomatsko generirajo, ko zaganjata vajine skripte. Takšnih datotek nočemo na repozitoriju, saj ustvarjajo nered. Datoteke, ki so lokalno na računalniku in nočemo, da se uploadajo na GitHub, dodamo v `.gitignore`, ki ga že imata na repozitoriju, vendar je prazen. Predlagam, da kopirata vsebino [te datoteke](https://github.com/github/gitignore/blob/main/Python.gitignore) v vajino `.gitignore` datoteko. Nato izbrišita mapo `__pycache__`, commitajta in pushajta spremembe na repozitorij. Naslednjič bi se ta mapa (in vsa ostala šara) potem morala ignorirati.

**Comment by juresternad** [comment]
Najlepša hvala za predlog. Za urejenost repozitorija sva sicer mislila poskrbeti v končni fazi projekta, a verjetno je res bolje, da to urejava sproti. Sem popravil.
