### ISSUE TITLE
Binder

### ISSUE THREAD

**Issue by jaanos** [juresternad/letalski-promet#2]
Glavni razlog za to, da poganjanje na Binderju ne deluje, je ta, da aplikacija uvozi knjižnico `regex`, ki je ni v osnovni namestitvi Pythona. Da se ta vključi v sistem, bo potrebno v datoteko `binder/requirements.txt` dodati vrstico `regex`.

Poleg tega bo potrebno v predlogah in pri preusmeritvah dosledno podajati poti s funkcijo `url` - tej podasta ime funkcije (brez začetne poševnice) in morebitne (poimenovane) parametre. Namesto
https://github.com/juresternad/letalski-promet/blob/b670b5aaa9f03e33da0f5bcb34f06c161527297d/letalski_promet.py#L98
bo tako potrebno narediti
```python
redirect(url('d', iz="-".join(iz.split()), do="-".join(do.split()), datum_odhoda=datum_odhoda,
             datum_prihoda=datum_vrnitve, razred=razred, enosmeren=enosmeren))
```
namesto
https://github.com/juresternad/letalski-promet/blob/b670b5aaa9f03e33da0f5bcb34f06c161527297d/views/base.html#L18
pa
```css
background-image: url('{{url("static", filename="/images/ozadje.jpeg"}}');
```

Poleg tega opažam, da uporabnik `javnost` nima pravic na tabelah in števcih - trenutno lahko te dodeljuje le @gapro8. Za osnovne pravice bo najlažje narediti
```sql
GRANT SELECT ON ALL TABLES IN SCHEMA public TO javnost;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO javnost;
```
Poleg tega bo seveda potrebno dodati še ustrezne pravice (`INSERT`, `UPDATE`, `DELETE`) na tistih tabelah, kjer je to potrebno.

**Comment by juresternad** [comment]
Hvala za vso pomoč. Odpravil sem vse napake v zvezi s povezavami in binder zdaj "skoraj" deluje. Edina težava, ki je ne uspem odpraviti, je odpiranje novega okna pri nakupu karte.  Kot razumem, se problem pojavi v vrstici `<a onclick="window.open('/kupi/{{let[7]}}?` (v [`views/dijkstra_let.html`]()).

https://github.com/juresternad/letalski-promet/blob/36d70ae1fca04c34a89edf0974d81004119171f2/views/dijkstra_let.html#L20-L27

Kako bi se dalo še to razrešiti?

**Comment by jaanos** [comment]
Tako bi moralo delovati:
```html
<a onclick="window.open('{{url("nakup_karte", id_leta=let[7]}}', ...); ...">
```
Morda se bo urejevalnik nekoliko zmedel in čudno pobarval kodo, a je treba upoštevati, da se najprej izvede koda znotraj zavitih oklepajev, ki skupaj s preostankom generira veljaven HTML.

**Comment by juresternad** [comment]
Zdaj deluje. Najlepša hvala!
